### ISSUE TITLE
graph displays locally but not in Binder

### ISSUE THREAD

**Issue by brianminsk** [cytoscape/ipycytoscape#273]
Any ideas why this graph displays in a local Jupyter Notebook but not on binder, please?

https://mybinder.org/v2/gh/brianminsk/binder_test/HEAD

**Comment by MridulS** [comment]
Could you create a new file (environment.yml) in that repo (https://github.com/brianminsk/binder_test) and add this config to it?
``` yaml
name: ipycytoscape
channels:
  - conda-forge
dependencies:
  - ipycytoscape>=1.0.3
  - jupyterlab=3
```
This will make sure the environment is correctly set up at binder.
